# Generated by Django 5.0.3 on 2024-03-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
